In [62]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from skimpy import clean_columns

In [104]:
landscape_cat = {
    "ag": [
        "Corn",
        "Cotton",
        "Rice",
        "Sorghum",
        "Soybeans",
        "Sunflower",
        "Peanuts",
        "Tobacco",
        "Sweet Corn",
        "Pop or Orn Corn",
        "Mint",
        "Barley",
        "Durum Wheat",
        "Spring Wheat",
        "Winter Wheat",
        "Other Small Grains",
        "Dbl Crop WinWht/Soybeans",
        "Rye",
        "Oats",
        "Millet",
        "Speltz",
        "Canola",
        "Flaxseed",
        "Safflower",
        "Rape Seed",
        "Mustard",
        "Alfalfa",
        "Other Hay/Non Alflafa",
        "Camelina",
        "Buckwheat",
        "Sugarbeets",
        "Dry Beans",
        "Potatoes",
        "Other Crops",
        "Sugarcane",
        "Sweet Potatoes",
        "Misc Vegs & Fruits",
        "Watermelons",
        "Onions",
        "Cucumbers",
        "Chick Peas",
        "Lentils",
        "Peas",
        "Tomatoes",
        "Caneberries",
        "Hops",
        "Herbs",
        "Clover/Wildflowers",
        "Sod/Grass Seed",
        "Switchgrass",
        "Cherries",
        "Peaches",
        "Apples",
        "Grapes",
        "Christmas Trees",
        "Other Tree Crops",
        "Citrus",
        "Pecans",
        "Almonds",
        "Walnuts",
        "Pears",
        "Pistachios",
        "Triticale",
        "Carrots",
        "Asparagus",
        "Garlic",
        "Cantaloupes",
        "Prunes",
        "Olives",
        "Oranges",
        "Honeydew Melons",
        "Broccoli",
        "Avocados",
        "Peppers",
        "Pomegranates",
        "Nectarines",
        "Greens",
        "Plums",
        "Strawberries",
        "Squash",
        "Apricots",
        "Vetch",
        "Dbl Crop WinWht/Corn",
        "Dbl Crop Oats/Corn",
        "Lettuce",
        "Dbl Crop Triticale/Corn",
        "Pumpkins",
        "Dbl Crop Lettuce/Durum Wht",
        "Dbl Crop Lettuce/Cantaloupe",
        "Dbl Crop Lettuce/Cotton",
        "Dbl Crop Lettuce/Barley",
        "Dbl Crop Durum Wht/Sorghum",
        "Dbl Crop Barley/Sorghum",
        "Dbl Crop WinWht/Sorghum",
        "Dbl Crop Barley/Corn",
        "Dbl Crop WinWht/Cotton",
        "Dbl Crop Soybeans/Cotton",
        "Dbl Crop Soybeans/Oats",
        "Dbl Crop Corn/Soybeans",
        "Blueberries",
        "Cabbage",
        "Cauliflower",
        "Celery",
        "Radishes",
        "Turnips",
        "Eggplants",
        "Gourds",
        "Cranberries",
        "Dbl Crop Barley/Soybeans",
        "Cropland",
    ],
    "nat": [
        "Forest",
        "Shrubland",
        "Barren",
        "Wetlands",
        "Nonag/Undefined",
        "Deciduous Forest",
        "Evergreen Forest",
        "Mixed Forest",
        "Shrubland",
        "Woody Wetlands",
        "Herbaceous Wetlands",
    ],
    "semi_nat": ["Grassland/Pasture", "Grass/Pasture"],
    "dev": [
        "Developed/Open Space",
        "Developed/Low Intensity",
        "Developed/Med Intensity",
        "Developed/High Intensity",
        "Barren",
    ],
    "other": ["Aquaculture", "Water", "Perennial Ice/Snow", "Open Water"],
}

In [105]:
def cdl_processing(cdl_metadata, qgis_csv):

    cdl_metadata["cdl_number"] = "VALUE_" + cdl_metadata["cdl_number"].astype("str")
    qgis_csv.rename(
        columns=cdl_metadata.set_index("cdl_number")["cdl_classification"], inplace=True
    )
    
    qgis_csv["Total"] = qgis_csv.sum(axis=1, numeric_only=True)
    qgis_csv['Ag'] = qgis_csv[qgis_csv.columns.intersection(landscape_cat['ag'])].sum(axis=1)
    qgis_csv["Ag_Prop"] = qgis_csv["Ag"] / qgis_csv["Total"]
    qgis_csv['Nat'] = qgis_csv[qgis_csv.columns.intersection(landscape_cat['nat'])].sum(axis=1)
    qgis_csv["Nat_Prop"] = qgis_csv["Nat"] / qgis_csv["Total"]
    qgis_csv['Semi_Nat'] = qgis_csv[qgis_csv.columns.intersection(landscape_cat['semi_nat'])].sum(axis=1)
    qgis_csv["Semi_Nat_Prop"] = qgis_csv["Semi_Nat"] / qgis_csv["Total"]
    qgis_csv['Dev'] = qgis_csv[qgis_csv.columns.intersection(landscape_cat['dev'])].sum(axis=1)
    qgis_csv["Dev_Prop"] = qgis_csv["Dev"] / qgis_csv["Total"]
    qgis_csv['Other'] = qgis_csv[qgis_csv.columns.intersection(landscape_cat['other'])].sum(axis=1)
    qgis_csv["Other_Prop"] = qgis_csv["Other"] / qgis_csv["Total"]
    #qgis_csv["Corn_Prop"] = qgis_csv["Corn"] / qgis_csv["Total"]
    #qgis_csv["Soybean_Prop"] = qgis_csv["Soybeans"] / qgis_csv["Total"]
    #qgis_csv["Wheat_Prop"] = qgis_csv["Winter Wheat"] / qgis_csv["Total"]
    qgis_csv["Forest_Prop"] = (qgis_csv.filter(like='Forest').sum(axis=1)) / qgis_csv["Total"]
    qgis_csv["Total_Nat_Prop"] = qgis_csv["Nat_Prop"] + qgis_csv["Semi_Nat_Prop"]

    return qgis_csv

In [106]:
metadata_2022 = pd.read_csv('cdl_metadata_ny_2022.csv')
metadata_2024 = pd.read_csv('cdl_metadata_ny_2022.csv')

In [107]:
metadata_2022

     cdl_number        cdl_classification
0             1                      Corn
1             2                    Cotton
2             3                      Rice
3             4                   Sorghum
4             5                  Soybeans
..          ...                       ...
128         247                   Turnips
129         248                 Eggplants
130         249                    Gourds
131         250               Cranberries
132         254  Dbl Crop Barley/Soybeans

[133 rows x 2 columns]

In [108]:
metadata_2024

     cdl_number        cdl_classification
0             1                      Corn
1             2                    Cotton
2             3                      Rice
3             4                   Sorghum
4             5                  Soybeans
..          ...                       ...
128         247                   Turnips
129         248                 Eggplants
130         249                    Gourds
131         250               Cranberries
132         254  Dbl Crop Barley/Soybeans

[133 rows x 2 columns]

In [109]:
qgis_2022 = pd.read_csv('2022_cdl.csv')
qgis_2024 = pd.read_csv('2024_cdl.csv')

In [110]:
qgis_2022

,Farm,Lat,Long,VALUE_1,VALUE_5,VALUE_12,VALUE_21,VALUE_24,VALUE_27,VALUE_28,...,VALUE_123,VALUE_124,VALUE_131,VALUE_141,VALUE_142,VALUE_143,VALUE_152,VALUE_176,VALUE_190,VALUE_195
0,Chaseholm,41.987886,-73.617804,36,3,0,5,0,1,2,...,11,0,1,1305,76,63,5,732,68,1
1,Wallbridge,41.774998,-73.651566,71,3,1,0,0,0,0,...,14,3,1,1766,14,48,1,752,171,3
2,JohnK,42.400617,-73.994206,6,1,0,0,0,0,0,...,20,0,2,938,705,770,3,270,205,12
3,Boone,42.544634,-74.033696,25,0,0,0,0,0,0,...,2,0,1,1898,69,642,2,186,60,37
4,Turner,42.226866,-76.997053,11,1,0,0,0,0,0,...,4,3,0,1221,323,780,2,514,8,1
5,Kuipers,42.652411,-78.247760,228,54,12,0,1,0,0,...,8,1,0,733,91,234,1,212,77,3
6,Honeyhill,42.787620,-77.681156,532,187,0,0,1,0,0,...,11,0,0,828,1,90,1,822,48,1
7,Rugenstein,43.062994,-77.303742,220,42,0,0,8,0,0,...,118,59,6,911,6,111,1,495,380,1
8,Eisele,42.158070,-74.802461,5,0,0,0,0,0,0,...,10,2,7,1909,92,311,3,415,17,2
9,Shephard,42.322393,-74.891982,10,1,0,0,0,4,0,...,7,2,0,1892,17,64,8,805,8,2

In [111]:
qgis_2024

,Farm,Lat,Long,VALUE_1,VALUE_4,VALUE_5,VALUE_6,VALUE_12,VALUE_21,VALUE_23,...,VALUE_176,VALUE_190,VALUE_195,VALUE_205,VALUE_206,VALUE_214,VALUE_219,VALUE_222,VALUE_228,VALUE_229
0,Chaseholm,41.959261,-73.608753,194,0,0,0,0,0,0,...,1075,27,0,0,0,0,0,0,0,0
1,Full Moon,41.753636,-74.122224,0,0,0,0,0,0,0,...,1312,14,0,0,0,0,0,0,0,0
2,Boone,42.514032,-74.047356,75,0,14,0,0,0,0,...,1677,119,8,0,0,0,0,0,0,0
3,Wilmar Farm,42.652490,-78.247704,64,10,20,0,0,0,0,...,716,16,0,0,17,0,0,3,0,0
4,Hendricksons Grazing Acres,42.622045,-78.134195,229,0,0,0,0,0,0,...,685,52,2,0,0,0,0,0,0,0
5,Tamberlane Farm,42.827978,-77.258460,0,0,1,0,0,0,0,...,595,69,0,0,0,1,0,0,0,0
6,Rugenstein,42.940091,-77.302841,588,1,20,0,0,1,0,...,1167,57,7,45,0,0,0,0,0,0
7,Charlie Reinshagen,42.378973,-74.666026,7,0,0,1,0,0,0,...,1204,6,0,0,0,0,0,0,0,0
8,Maks Melvan,42.365790,-74.589692,0,0,0,0,0,0,0,...,1683,6,0,0,0,0,0,0,0,0
9,LaurDom Cattle Co.,42.265233,-74.757086,0,0,0,0,0,0,0,...,1025,6,0,0,0,0,0,0,0,0
10,Stony Creek Farm,42.252111,-75.107264,0,0,0,0,0,0,0,...,951,3,2,0,0,0,0,0,0,0
11,Porco,43.032660,-74.769400,562,0,177,0,1,2,0,...,2170,19,0,0,0,0,0,0,105,0
12,Young,42.881300,-74.833800,0,0,0,0,0,0,0,...,1845,167,1,0,0,0,0,0,0,0
13,Devine Gardens,42.915420,-75.747100,2,0,0,0,0,0,0,...,901,242,8,2,0,0,0,0,0,0
14,Essex Farm,44.309224,-73.369184,18,0,2,34,0,13,0,...,1944,222,2,0,0,0,0,0,0,6
15,Daona,43.879372,-73.315943,700,0,1,0,0,0,2,...,1759,24,0,0,0,0,0,0,0,0
16,KZ,44.214088,-73.444221,2,0,0,0,1,0,0,...,2016,72,1,0,0,0,0,0,0,0
17,J+R Pierce,44.785972,-73.520933,0,0,0,0,0,0,0,...,956,401,42,0,0,0,0,0,0,0
18,Donahues,44.783729,-74.454221,0,0,0,0,0,0,0,...,1000,180,0,0,0,0,1,0,0,0

In [112]:
props_2022 = cdl_processing(metadata_2022, qgis_2022)
props_2022.to_csv('2022_cdl_props.csv')

In [113]:
props_2022

,Farm,Lat,Long,Corn,Soybeans,Sweet Corn,Barley,Winter Wheat,Rye,Oats,...,Nat,Nat_Prop,Semi_Nat,Semi_Nat_Prop,Dev,Dev_Prop,Other,Other_Prop,Forest_Prop,Total_Nat_Prop
0,Chaseholm,41.987886,-73.617804,36,3,0,5,0,1,2,...,1519,0.481249,732,0.231912,181,0.057344,0.0,0.0,0.457488,0.713161
1,Wallbridge,41.774998,-73.651566,71,3,1,0,0,0,0,...,2004,0.635560,752,0.238494,166,0.052646,0.0,0.0,0.579743,0.874054
2,JohnK,42.400617,-73.994206,6,1,0,0,0,0,0,...,2635,0.827730,270,0.084815,203,0.063768,0.0,0.0,0.757993,0.912544
3,Boone,42.544634,-74.033696,25,0,0,0,0,0,0,...,2709,0.850146,186,0.058371,89,0.027930,0.0,0.0,0.818764,0.908517
4,Turner,42.226866,-76.997053,11,1,0,0,0,0,0,...,2335,0.737936,514,0.162441,217,0.068579,0.0,0.0,0.734460,0.900377
5,Kuipers,42.652411,-78.247760,228,54,12,0,1,0,0,...,1139,0.357456,212,0.066533,201,0.063081,0.0,0.0,0.332036,0.423989
6,Honeyhill,42.787620,-77.681156,532,187,0,0,1,0,0,...,969,0.302992,822,0.257027,316,0.098808,0.0,0.0,0.287358,0.560019
7,Rugenstein,43.062994,-77.303742,220,42,0,0,8,0,0,...,1416,0.440743,495,0.154073,1037,0.322776,0.0,0.0,0.319974,0.594816
8,Eisele,42.158070,-74.802461,5,0,0,0,0,0,0,...,2341,0.740505,415,0.131273,181,0.057254,0.0,0.0,0.731332,0.871778
9,Shephard,42.322393,-74.891982,10,1,0,0,0,4,0,...,1991,0.626410,805,0.253270,174,0.054744,0.0,0.0,0.620747,0.879679

In [114]:

qgis_2024["Total"] = qgis_2024.sum(axis=1, numeric_only=True)

In [115]:
props_2024 = cdl_processing(metadata_2024, qgis_2024)
props_2024.to_csv('2024_cdl_props.csv')